on: push

jobs:
  build-and-publish:
    name: 'Build and Publish'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: 15.6

      - name: 'Install Dependencies'
        run: yarn

      - name: 'Build'
        run: yarn build

      - name: 'Publish to NPM'
      - run: npm publish --access public
      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
